modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/mahmudindev/mcmod-largebiomesdimension"
license = "ARR"

[[mods]]
modId = "largebiomesdimension"
version = "${version}"
displayName = "Large Biomes Dimension"
authors = "mahmudindev"
description = '''
Add large biomes world type as separate dimension.
'''
logoFile = "assets/largebiomesdimension/icon.png"

[[dependencies.largebiomesdimension]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.largebiomesdimension]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.largebiomesdimension]]
modId = "dimensionfixer"
mandatory = true
versionRange = "[0.0.9,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.largebiomesdimension]]
modId = "worldportal"
mandatory = true
versionRange = "[0.0.9,)"
ordering = "NONE"
side = "SERVER"
